# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'house_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PublicHousingAuthorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, db_column='X', null=True)),
                ('y', models.FloatField(blank=True, db_column='Y', null=True)),
                ('formal_participant_name', models.TextField(blank=True, db_column='FORMAL_PARTICIPANT_NAME', null=True)),
                ('ha_phn_num', models.BigIntegerField(blank=True, db_column='HA_PHN_NUM', null=True)),
                ('ha_email_addr_text', models.TextField(blank=True, db_column='HA_EMAIL_ADDR_TEXT', null=True)),
                ('phas_designation', models.TextField(blank=True, db_column='PHAS_DESIGNATION', null=True)),
                ('ha_low_rent_size_category', models.TextField(blank=True, db_column='HA_LOW_RENT_SIZE_CATEGORY', null=True)),
                ('ha_program_type', models.TextField(blank=True, db_column='HA_PROGRAM_TYPE', null=True)),
                ('total_units', models.IntegerField(blank=True, db_column='TOTAL_UNITS', null=True)),
                ('total_occupied', models.IntegerField(blank=True, db_column='TOTAL_OCCUPIED', null=True)),
                ('pct_occupied', models.FloatField(blank=True, db_column='PCT_OCCUPIED', null=True)),
                ('pha_total_units', models.IntegerField(blank=True, db_column='PHA_TOTAL_UNITS', null=True)),
                ('spending_per_month', models.IntegerField(blank=True, db_column='SPENDING_PER_MONTH', null=True)),
                ('chldrn_mbr_cnt', models.IntegerField(blank=True, db_column='CHLDRN_MBR_CNT', null=True)),
                ('eldly_prcnt', models.FloatField(blank=True, db_column='ELDLY_PRCNT', null=True)),
                ('pct_disabled_lt62_all', models.FloatField(blank=True, db_column='PCT_DISABLED_LT62_ALL', null=True)),
                ('pct_lt80_median', models.FloatField(blank=True, db_column='PCT_LT80_MEDIAN', null=True)),
                ('median_inc_amnt', models.IntegerField(blank=True, db_column='MEDIAN_INC_AMNT', null=True)),
                ('curcnty_nm', models.TextField(blank=True, db_column='CURCNTY_NM', null=True)),
                ('std_addr', models.TextField(blank=True, db_column='STD_ADDR', null=True)),
                ('std_city', models.TextField(blank=True, db_column='STD_CITY', null=True)),
                ('std_st', models.TextField(blank=True, db_column='STD_ST', null=True)),
                ('std_zip5', models.IntegerField(blank=True, db_column='STD_ZIP5', null=True)),
                ('lat', models.FloatField(blank=True, db_column='LAT', null=True)),
                ('lon', models.FloatField(blank=True, db_column='LON', null=True)),
            ],
            options={
                'db_table': 'Public_Housing_Authorities',
                'managed': False,
            },
        ),
    ]
